# spring.datasource.url=jdbc:mysql://localhost:3306/fashionweb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
# spring.datasource.username=root
# spring.datasource.password=123456

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.open-in-view=false
# spring.devtools.restart.enabled=false
# allowPublicKeyRetrieval=true
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:mysql://localhost:3306/fashionweb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.devtools.restart.enabled=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET:ha-fashion-secret-key-ha-fashion-secret-key-2026}
jwt.expiration=86400000

payos.client-id=cb8cbb97-69ce-4b04-8a21-d41591fd0eb8
payos.api-key=27097ac3-d1b2-4ada-8c21-261f2869bf6b
payos.checksum-key=a13c0fd4dde8575da309a91530750b05622d466b0e6aff0e470bc0809aed2ad1

